"""Add non_food_category and story fields to Item model

Revision ID: 6eba35c78e57
Revises: de2fc318e447
Create Date: 2024-10-19 03:04:04.875818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6eba35c78e57'
down_revision = 'de2fc318e447'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('non_food_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('story', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('story')
        batch_op.drop_column('non_food_category')

    # ### end Alembic commands ###
