"""Added image field to Item model

Revision ID: 849174143e1d
Revises: ec7cb6cad49d
Create Date: 2024-10-19 06:04:40.416591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849174143e1d'
down_revision = 'ec7cb6cad49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
