"""Add allocated_to to Item model

Revision ID: de2fc318e447
Revises: ab6c42133601
Create Date: 2024-10-19 01:54:07.062677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2fc318e447'
down_revision = 'ab6c42133601'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allocated_to', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['allocated_to'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('allocated_to')

    # ### end Alembic commands ###
